# Generated by Django 3.2.5 on 2021-10-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchedPairs',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('missingName', models.CharField(blank=True, db_column='missing_name', max_length=255, null=True)),
                ('reportedName', models.CharField(blank=True, db_column='reported_name', max_length=255, null=True)),
                ('missingImage', models.ImageField(db_column='missing_image', null=True, upload_to='matched')),
                ('reportedImage', models.ImageField(db_column='reported_image', null=True, upload_to='matched')),
            ],
            options={
                'db_table': 'MatchedPairs',
            },
        ),
    ]
