# Generated by Django 3.2.5 on 2021-07-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_auto_20210716_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingpeople',
            name='name',
            field=models.CharField(blank=True, db_column='name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reportedpeople',
            name='name',
            field=models.CharField(blank=True, db_column='name', max_length=255, null=True),
        ),
    ]
