# Generated by Django 3.2.5 on 2021-10-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_matchedpairs'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingpeople',
            name='date',
            field=models.DateField(blank=True, db_column='date', null=True),
        ),
    ]
