# Generated by Django 3.2.5 on 2021-11-04 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0004_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
