# Generated by Django 3.2.5 on 2021-07-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0004_auto_20210716_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingpeople',
            name='image',
            field=models.ImageField(db_column='image', null=True, upload_to='missing/finding'),
        ),
    ]
