# Generated by Django 3.2.5 on 2021-11-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0005_delete_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingpeople',
            name='file',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
