# Generated by Django 3.2.5 on 2021-07-17 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0005_alter_missingpeople_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingpeople',
            name='gender',
            field=models.CharField(blank=True, db_column='gender', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='missingpeople',
            name='description',
            field=models.CharField(blank=True, db_column='description', max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='missingpeople',
            name='image',
            field=models.ImageField(db_column='image', null=True, upload_to='missing/<django.db.models.fields.CharField>/<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='missingpeople',
            name='status',
            field=models.CharField(blank=True, db_column='status', max_length=255, null=True),
        ),
    ]
