# Generated by Django 3.2.5 on 2021-11-06 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0006_missingpeople_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingpeople',
            name='file',
        ),
    ]
