# Generated by Django 3.2.5 on 2021-07-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0006_auto_20210717_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportedpeople',
            name='image',
        ),
        migrations.AddField(
            model_name='reportedpeople',
            name='gender',
            field=models.CharField(blank=True, db_column='gender', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reportedpeople',
            name='status',
            field=models.CharField(blank=True, db_column='status', max_length=255, null=True),
        ),
    ]
