# Generated by Django 3.2.5 on 2021-07-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0007_auto_20210717_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingpeople',
            name='image',
            field=models.ImageField(db_column='image', null=True, upload_to='missing/'),
        ),
    ]
