# Generated by Django 3.2.5 on 2021-07-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0008_alter_missingpeople_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingpeople',
            name='image',
            field=models.ImageField(db_column='image', null=True, upload_to='missing\\<django.db.models.fields.CharField>\\<django.db.models.fields.CharField>'),
        ),
    ]
